### ISSUE TITLE
Tent given Id on create not use

### ISSUE THREAD

**Issue by khionu** [skyjay1/Nomadic-Tents#10]
As a pack developer, I want to give everyone a small tent to start with. There are a couple ways I can do it, but I wanted to include it in their backpack. This means crafting the tent, and then that tent being copied in each backpack.

The change to fix this would require tents not being bound to a spot in the tent dimension until first use of that item. This allows an uninitialized tent item to be copied freely, and each copy being able to be used to make its own interior.

**Comment by khionu** [comment]
~~Additionally, might I recommend using an ID system, so pack developers don't scratch their head over how to distribute tents? Because I have no idea what this NBT data means if the "offset" is not the means of the item known what interior it belongs to~~

My mistake. VCS error made my script contain old data.

**Comment by skyjay1** [comment]
I'll see if I can make this adjustment, it does seem like better gameplay. And actually the idea of a single location ID isn't bad, the only downside is that existing tents and worlds would have to start fresh if I change the math (again).

**Comment by skyjay1** [comment]
Added in 9.4.0
Let me know if there are any problems :)

**Comment by khionu** [comment]
Wonderful, will be testing soon!
