### ISSUE TITLE
Nether and Aether portals won't ignite in Tent dimension

### ISSUE THREAD

**Issue by JaceSilverwave** [skyjay1/Nomadic-Tents#17]
As mentioned, when using a flint and steel on a nether portal, or a water bucket on a glowstone portal for the aether, it will not light either. I am running the latest version of Nomadic Tents in the Rougelike Adventures and Dungeons modpack. I am unsure if this is an intended feature so that players cannot access other dimensions from inside the tent, but it would be nice if I could have an on-the-go portal setup in my tent.

**Comment by skyjay1** [comment]
This is default Minecraft behavior and cannot be changed without some serious hackery. You may notice, for example, that Minecraft prevents creation of Nether portals in the End. This is done by blocking ALL Nether portals EXCEPT in the Overworld OR the Nether.
As for Aether portals, it's likely that the author purposely added the same conditions. You should contact the mod author of Aether about an option to allow their portals in other dimensions (or check their config, the option may already exist).
