### ISSUE TITLE
[1.12.2] Random server crash: "Exception initializing level"

### ISSUE THREAD

**Issue by TheShelterProject** [skyjay1/Nomadic-Tents#2]
Hello,

Sometimes, the server crash during startup. 

**Mods list:**
Forge 14.23.5.2796
IvToolkit 1.3.3 ( _requiered for RecurrentComplex_ ) [[Curseforge]](https://minecraft.curseforge.com/projects/ivtoolkit) [[Github]](https://github.com/Ivorforce/IvToolkit)
NomadicTents 9.01
RecurrentComplex 1.4.7 [[Curseforge]](https://minecraft.curseforge.com/projects/recurrent-complex) [[Github]](https://github.com/Ivorforce/RecurrentComplex)
Sponge 7.1.4

**Logs:**
[Latest.log](https://pastebin.com/raw/E5Pnv1ez).
[Crash Report](https://pastebin.com/raw/XQxEr135).

**Comment by skyjay1** [comment]
Thank you for letting me know. It looks like I need to fix my custom biome registration. At first I thought it was just the core mod complaining, but it seems minecraft hit an error too

**Comment by skyjay1** [comment]
I've updated Nomadic Tents and hopefully fixed Biome registration. Try it out and let me know if it still crashes :D
