### ISSUE TITLE
Can't push entities into tent

### ISSUE THREAD

**Issue by afolk2** [skyjay1/Nomadic-Tents#22]
[permissions]
	#When true, non-player entities can enter the tent by walking through the door
	"Allow Entity Walk-In" = true

Expected:
When I push a chicken into the door it teleported into the tent.

Result:
The entity does not go into the tent. Tried with other animals.

Steps to recreate:
Make sure the config is set to true. Set up a Large Yurt/Bedouin/Teepee. Try to push an entity through

**Comment by skyjay1** [comment]
If you are using Nomadic Tents for 1.14, this is a known bug. Player and entity teleport-on-collision is disabled until I can get it to work correctly.
If you are using a different version of Nomadic Tents, please specify

**Comment by afolk2** [comment]
You are correct, 1.14, sorry about that.
