### ISSUE TITLE
Lan world, player can't log in after logging out in a Large Yurt

### ISSUE THREAD

**Issue by afolk2** [skyjay1/Nomadic-Tents#23]
The player could not log in after logging out in a Large Yurt. The world loading screen wouldn't move past "Loading". The player tried cancelling and then logging back in again to the same issue. The player joins the world but the loading screen doesn't go away so they can't interact with anything. I teleported the player out of the Yurt, when they tried to join the world again it connected.

**Comment by skyjay1** [comment]
There have been a couple reports about Nomadic Tents for 1.14 not working on servers. I'll look into it. If you are using a version that is NOT for 1.14, please specify.

**Comment by afolk2** [comment]
It is 1.14, thank you for letting me know.

**Comment by Leprican** [comment]
This is probably related to this issue, I keep having world crashes after logging out in a fully upgraded tent,
Localized private world no LAN. can log out outside of tent with no issue, game 1.14 mod version 10.0.1 beta

**Comment by skyjay1** [comment]
Please let me know if this is still happening as of release 10.0.2

**Comment by Leprican** [comment]
Tested, Seems to be fixed, only had a few dropping into the void issues that that is most likely due to loading time rather than mod issues - although I can't test in server I don't have access to anyone running it nor do I have one myself
