### ISSUE TITLE
Tent & dirt mis-aligned

### ISSUE THREAD

**Issue by pip69** [skyjay1/Nomadic-Tents#26]
When I upgrade from the Giant Shamiyana to the Mega, the walls expanded, but the dirt (unbreakable) didn't change.
The side walls had expanded 1 block, and the back wall expanded 2 blocks.  This left 1 space to fall out of the tent.
When upgraded the tent I had stuff in the tent when I upgraded, I also expanded the dirt layer down 1 at the same time.  The layer down worked as intended.

**Comment by AllieWade** [comment]
I've run into this as well, I was putting off reporting it until I did some more testing. It appears that when you upgrade the tent size and depth at the same time (without going back into the tent in between), the depth gets increased but the borders conform to the tent's original dimensions instead of its new ones.

**Comment by skyjay1** [comment]
What version of Nomadic Tents? I think I ran into this and fixed it but haven't released a new build, but I could be thinking of something else.

**Comment by AllieWade** [comment]
Minecraft: 1.12.2
Forge: 14.23.5.2847
Mods installed: Literally only NomadicTents-1.12.2-9.5.0.jar

Steps:
1. Load into world, remember that I really should install JEI on my test platform when I'm testing things that involve items.
2. Give myself like a stack of yurt walls, a super tent mallet, you get the idea.
3. Place the tent, whack it with the mallet, enter it once.
4. Exit the tent, whack it with a mallet.
3. Attempt to open the crafting table gui with the tent in my hand, placing the tent on top of the crafting table. Whack it with a mallet twice to build and remove it.
4. Upgrade the tent all the way to mega-yurt
5. Fully upgrade the tent's depth.
6. Re-place, re-whack, and re-enter the tent.
7. ???
8. [Profit.](https://imgur.com/a/6aJst6H)

[And here's a log.](https://paste.dimdev.org/felaxifene.md)

**Comment by skyjay1** [comment]
Thank you, I'll look into it. Most likely I'm checking for specific update types in the wrong order.

**Comment by skyjay1** [comment]
Confirmed that this is a bug. I fixed it in the 1.14 release but must not have gotten to fixing it in 1.12. Thank you for reminding me :)
