### ISSUE TITLE
Day skips w/o sleeping in tent

### ISSUE THREAD

**Issue by FluffiKiki** [skyjay1/Nomadic-Tents#28]
Hello, I do not have proper pictures of this incident, as it is more of an action, but I've experienced in the latest 1.14 version that when I enter in a tent (just right click the door and enter), it'll skip to morning without me sleeping in a bed. This experience has happened about 3 times while it was the middle of the day, not just when it was sunset or night.

**Comment by skyjay1** [comment]
Do you mean that the overworld skips to sunrise or that the tent dimension skips to sunrise?  Or both?

**Comment by FluffiKiki** [comment]
Both. Or at least, once I exit the tent after I can't go to bed, it'll skip to sunrise.

**Comment by skyjay1** [comment]
Can you explain what you mean by "can't go to bed?" If you started to sleep on a bed, my code might have thought you slept all the way...

**Comment by skyjay1** [comment]
Also is this a LAN or multi-player world?

**Comment by FluffiKiki** [comment]
Like once I go in the tent, it'll give me the message "You can only sleep during the night or thunderstorms" or something along those lines.

**Comment by FluffiKiki** [comment]
And it is single player

**Comment by skyjay1** [comment]
Thank you. I'll look into it, I only change the time in one place in the code, but the event may be fired at times I don't expect.

**Comment by skyjay1** [comment]
May or may not be fixed in the latest release (10.0.2). Let me know if it's still a problem
