### ISSUE TITLE
No Config being generated.

### ISSUE THREAD

**Issue by Gunzoffire** [skyjay1/Nomadic-Tents#31]
Mod Version - 1.14.4-10.0.1-beta.jar
Forge Version - 1.14.4-forge-28.1.61

No config is being generated not sure if its intentional to not generate one since its beta.

**Comment by skyjay1** [comment]
In 1.14, config files are now saved per-world. To find the config for this mod go to your .minecraft folder (if using Windows, go to %appdata% to get there). Click on "saves", select the name of the world, and go into "serverconfig". There you will find a file named "nomadictents-server.toml" which is the config file for this mod. Hope that helps
