### ISSUE TITLE
Depth upgrade doesnt work? 

### ISSUE THREAD

**Issue by TehFoxFire** [skyjay1/Nomadic-Tents#32]
https://i.imgur.com/8nhZcX4.png
Im having issues upgrading the tents as it doesnt show an output in the table.

**Comment by skyjay1** [comment]
Did you add the other upgrades first? The depth upgrades have to be applied in order from stone > iron > gold > obsidian > diamond. Even the mega tents need all other upgrades first in order to accept the diamond upgrade

**Comment by TehFoxFire** [comment]
Ah, now I feel like an idiot!
