### ISSUE TITLE
spawning outside the tent when it first generates

### ISSUE THREAD

**Issue by gravysamich** [skyjay1/Nomadic-Tents#35]
this has happened to me quite a bit. 

i am using Nomadic Tents 10.0.2.

this is way more common on a server too. my only solution is to use spectator mode to enter the tent again and i can only do that because i have forgiving void installed so i don't die when i fall into the the void.

everything seems to work fine once the tent is spawn though.

**Comment by Qsandas** [comment]
It's not just when it first generates either. Every time I enter my Tepee, there seems to be about a 25% chance that I will fall before the blocks inside render and die in the void. It's a minor inconvenience when you have certain mods, but maybe you should put the tent in a bedrock open-top cube perhaps? Or just have a pool of water below the tent area, just lower than the maximum depth upgrade?

**Comment by skyjay1** [comment]
I have been unable to reproduce this bug. What other mods are you using? If there are some world generation or other dimension-heavy mods, it could be that they are delaying my code from running in time. Other than that, I'm not sure how to solve this problem.

**Comment by Qsandas** [comment]
That's probably it. But for anyone else having the problem after the initial generation, I've found that chunkloading the tent stops the problem.

**Comment by HotBuns291** [comment]
I have the same issue of spawning out of my tent every time I go inside. It only happens to me if I have carpet placed on the block I spawn on after walking inside. Once I remove the carpet the problem stops. I am using the 11.0.0-beta

**Comment by skyjay1** [comment]
1.15 is no longer supported. Sorry for any inconvenience.
