### ISSUE TITLE
Yurt & Bedouin generating without exit door

### ISSUE THREAD

**Issue by MechanicalDragon0687** [skyjay1/Nomadic-Tents#39]
mc 1.12.2
latest forge  (14.23.5.2847)
nomadic tents 9.5.2 

When building a yurt, once entered, it does not have an exit door.

Attempted both a small yurt and a medium yurt, same issue.

with cheats disabled in single player, this leaves the player in a dimension with no way out

**Comment by MechanicalDragon0687** [comment]
tested all small models, Bedouin and Yurt have no exit doors
Teepee has the top half of the door but it is 1 block lower than it should be and the bottom exit block is missing
the other models generated fine with default colouring

in testing this issue, it seems the door appears when entering the structure the 2nd time. i tested this by going into gamemode 3 (spectator) and flying to a working tent then changing back to gm 1 (creative) i could then exit using the other tent's exit and upon re-entering the broken structure, the door would be created correctly

**Comment by Rsslone** [comment]
I am having this issue as well on the same tents. Did we ever find a fix?

**Comment by clonetrooper277** [comment]
I just got this bug myself. OOF... how do i even get out? Kill myself with keep inventory on?

**Comment by skyjay1** [comment]
1.12 is no longer supported. Sorry for any inconvenience.
