### ISSUE TITLE
[Suggestion] Spawn point setting

### ISSUE THREAD

**Issue by ghost** [skyjay1/Nomadic-Tents#4]
I know it's been mentioned, but I thought I'd make a suggestion (here rather than on Curse). A number of mods mess with the player spawn. Natura has the ghost wood pylon, I think it's Morpheus that lets players set their spawn point during the day. Simulated nights draws out the sleep cycle to let things happen overnight. etc.

Is it possible to set a player's overworld spawn when they sleep inside the tent (keep a list in the tent data) and then remove that spawn when the tent or bed is broken (check to see if it's still that player's spawn first)?

**Comment by skyjay1** [comment]
I'm not sure I understand correctly. In Minecraft Forge, it is possible to have multiple spawn locations, one for every dimension. When a player sleeps inside a tent, the mod does nothing -- Forge, on the other hand, adds the player's location as the default spawn location IF AND ONLY IF you die inside a tent. If you die in, say, the Overworld, Forge looks up your spawn location in the Overworld and sends you there. 
I'm not sure what other mods do -- if they set a single spawn point regardless of dimension, then turn off "Allow Respawn Logic" in the config so this mod does not interfere. If you want players who die in the Overworld to respawn in their tent, that's possible but would definitely interfere with the custom-spawn-point mods you mentioned. Can you give an example of what it is you want the mod to do?

**Comment by ghost** [comment]
I would like the tent to work as a bed for the dimension it's set up in.
If I travel 100 chunks, set up my tent, go inside and sleep, then when I die mining I should respawn by the tent, not at world spawn. Right now I have to sleep outside, but I'm pretty sure it's possible to make it so sleeping in the tent also sets the player's spawn point in the outer dimension.

**Comment by skyjay1** [comment]
Added in 9.0.5. Let me know if it fits what you were describing, but even if not, I think it's a really cool addition.
Thank you for the suggestion!

**Comment by ghost** [comment]
Exactly! I like. I'm doing Enigmatica 2 right now, but you are tempting me away.

**Comment by ghost** [comment]
And thank you!
