### ISSUE TITLE
Tent is spawning without an interior wall.

### ISSUE THREAD

**Issue by ARandomCrusader** [skyjay1/Nomadic-Tents#49]
I'm playing on 1.7.10, so that might be a part of the issue, but I'd just like to report it to see if there's any known way to fix this.
![2020-05-19_10 23 53](https://user-images.githubusercontent.com/65613267/82346327-ed74a480-99bb-11ea-937a-e129c2e91325.png)

**Comment by ARandomCrusader** [comment]
Just as a quick note, this happens every time I enter ANY of the tents, not just specifically the Large Yurt

**Comment by skyjay1** [comment]
Thank you for the report, however 1.7.10 is no longer supported.
