### ISSUE TITLE
Exiting Tent Spawning at wrong location

### ISSUE THREAD

**Issue by ClaudiusMinimus** [skyjay1/Nomadic-Tents#50]
I am developing a mod pack and would like to include your mod. After normally entering a tent, and upon returning the player is spawned at the wrong location. The pack is built around the [Ultra Amplified Dimension](https://www.curseforge.com/minecraft/mc-mods/ultra-amplified-mod), with it as the overworld.

OS: Linux Mint 19.3
Minecraft 1.15.2
Java: Oracle Java 1.8.0_212
Forge version: 31.2.0
NomadicTents-1.15.2-11.0.0-beta

Mods:
 [1.15.2] SecurityCraft v1.8.18.1
 Abnormals-Core-1.15.2-v1.0.4
 AdChimneys-1.15.2-5.0.5.0-build.0040
 additional_lights-1.15.2-1.1.1
 AI-Improvements-1.15.2-0.3.0
 AkashicTome-1.3-13
 AmbientSounds_v3.0.20_mc1.15.2
 angelring-1.15.2-1.2.0
 Apotheosis-1.15.2-3.1.2
 AppleSkin-mc1.15.2-forge-1.0.13
 Aquaculture-1.15.2-2.0.14
 AutoRegLib-1.5-40
 BetterAdvancements-1.15.2-0.1.0.96
 betterwithminecolonies-1.15.2-1.15.16
 bluepower-1.15.2-0.4.188-alpha-universal
 BonsaiTrees-2.1.2.6
 Bookshelf-1.15.2-5.6.38
 borderless-1.15.2-1.1.0
 Botania-r1.15-384
 BotanyPots-1.15.2-2.0.14
 branders-enhanced-mob-spawners-v1.15.2-1.5.4
 buildinggadgets-3.3.5
 bwncr-1.15.1-3.6.13
 caelus-FORGE-1.15.2-2.0-beta2
 cc-tweaked-1.15.2-1.88.1
 ceramicbucket-1.2.2-1.14.4_1.15.X
 ChineseWorkshop-1.15.2-2.4.4
 citadel-1.1.5-1.15.2
 Clay WorldGen-1.1.0-1.15.1
 clayconversion-1.15-1.0
 ClickMachine-1.15.2-3.0.2
 clockout-1.15.2-1.0.0
 Clumps-5.0.2
 cofh_core-1.15.2-0.4.0b
 comforts-FORGE-1.15.2-2.0.0.2
 Compressium-1.0.18
 config-2-3.0
 controllable-1.15.2-0.8.0
 Controlling-6.1.4
 CookingForBlockheads_1.15.2-8.0.1
 corail_pillar-4.5.4-1.15.1
 corpse-1.15.2-1.0.4
 CosmeticArmorReworked-1.15.2-v3a
 CraftingCraft_1.15.1-8.0.0
 craftingstation-3.1.0
 CraftingTweaks_1.15.1-11.0.0
 CraftTweaker-1.15.2-6.0.0.24
 crashutilities-2.2
 Cucumber-1.15.2-3.0.6
 curios-FORGE-1.15.2-2.0.2.2
 cursedearth-2.1
 Cyclic-1.15.2-0.4.1
 dankstorage-2.6
 DarkUtilities-1.15.2-3.0.5
 DefaultOptions_1.15.2-11.0.1
 defaultworldtype-1.15.2-1.0.1
 Disenchanting-forge_1.15.2-1.5.0
 DoubleSlabs-1.15-2.3.0
 elevatorid-1.15.2-1.7.1
 enderchests-1.15-1.6.1
 endertanks-1.15-1.8.1
 engineerstools-1.15.2-1.0.7
 ensorcellation-1.15.2-0.4.1b
 EquipmentTooltips-1.15.2-1.4.0+11
 extratags-1.1
 fancymenu_1.0.1_MC_1.15-1.15.2
 farlanders-1.15.2-1.1.2
 FarmingForBlockheads_1.15.2-6.1.2
 FastFurnace-1.15.1-3.0.0
 FastLeafDecay-v22
 FastWorkbench-1.15.1-3.0.0
 fixselecteditemtext-1.0
 FluxNetworks-1.15.2-5.0.1-2
 forbidden_arcanus-1.15.2-1.3.1
 ForgeEndertech-1.15.2-6.0.3.0-build.0036
 FruitTrees-1.15.2-1.3.0
 ftb-chunks-1.1.0.12
 ftb-gui-library-1.0.0.14
 ftb-quests-2.0.2.246
 furniture-7.0.0-pre16-1.15.1
 glassential-forge-1.15.2-1.1.2
 globaldatapack-1.15.2-1.3
 globalxp-1.15.2-v1.4.11
 Gobber2-1.15.2-2.2.95
 good-nights-sleep-1.15.2-1.0.3
 Industrial Agriculture[Core]-1.15.2-1.7.0
 Industrial Agriculture[Mekanism]-1.15.2-1.6.1
 industrial-foregoing-1.15.2-2.3.0-6f57752
 inventorysorter-1.15.2-17.0.0
 item-filters-2.2.0.14
 JAOPCA-1.15.2-3.2.0.9
 jei-1.15.2-6.0.0.4
 JEITweaker-1.0.1
 journeymap-1.15.2-5.7.0b2
 justenoughbeacons-2.0
 JustEnoughCalculation-1.15.2-3.6.1
 JustEnoughResources-1.15.2-0.10.1.77
 Kiwi-1.15.2-2.7.1
 KleeSlabs_1.15.2-8.0.0
 LargeFluidTank-15.2.9
 libnonymous-1.15.2-1.1.1.5
 lightestlampsmod-3.4.1
 LightOverlay-4.6.1
 lithium-mc1.15.2-forge-0.4.6-rc3-mod
 Lollipop-1.15.2-1.0.15
 longfallboots-1.4.0c
 Mantle-1.15.2-1.5.15
 mcjtylib-1.15-4.1.0-beta
 mcw-bridges-1.0.4fix-mc1.15.2
 mcw-doors-1.0.0-mc1.15.2
 mcw-furniture-1.0.1-mc1.15.1 1.15.2
 mcw-roofs-1.0.2-mc1.15.2_1.15.1
 mcw-windows-1.0.1-mc1.15.2_1.15.1
 Mekanism-1.15.2-9.10.6.419
 MekanismGenerators-1.15.2-9.10.6.419
 MekanismTools-1.15.2-9.10.6.419
 metalbarrels-2.1
 minecolonies-1.15.2-0.11.949-universal-universal
 mining_dimension-1.15.2-1.0.4
 mining-helmet-1.15.2-1.0.8
 MixinBootstrap-1.0.3
 mobcatcher-2.2
 Morpheus-1.15.2-4.2.50
 MouseTweaks-2.13-mc1.15.1
 MysticalAgradditions-1.15.2-3.0.0
 MysticalAgriculture-1.15.2-3.0.5
 NaturesAura-28.1
 NaturesCompass-1.15.2-1.8.5
 NetherPortalFix_1.15.2-6.0.2
 NomadicTents-1.15.2-11.0.0-beta
 noRecipeBook_v1.5.4formc1.15.2
 OpenLoader-1.15.2-4.0.5
 OreExcavation-1.7.151
 Patchouli-1.15.2-1.2-33
 performant-1.15-2.11m
 PickleTweaks-1.15.2-4.0.3
 Placebo-1.15.2-3.0.2
 Powah-1.15.2-1.1.14
 Project Essentials Backup-1.15.2-1.0.1
 Project Essentials Core-MOD-1.15.2-1.1.0
 QuantumStorage-1.15.2-5.1.1
 Quark-r2.1-237
 QuarkOddities-1.15.2
 randompatches-1.15.2-1.21.1.2
 rangedpumps-0.7.1
 rats-5.3.0-1.15.2
 reap-1.12.4
 ReAuth-1.14-1.15-3.8.1
 refinedpipes-0.4.1
 refinedstorage-1.8.3
 refinedstorageaddons-0.6.1
 Reliquary-1.15.2-1.3.4.995
 rftoolsbase-1.15-1.1.1-beta
 rftoolsbuilder-1.15-2.1.2-beta
 rftoolspower-1.15-2.1.1-beta
 rftoolsstorage-1.15-1.1.3-beta
 rftoolsutility-1.15-2.1.3-beta
 ropebridge-1.15.1-1.2
 roughmobsrevamped-1.15.2-4.1.2
 rsgauges-1.15.2-1.2.3
 ruins-1.15.1.3
 ScalableCatsForce-2.13.2-build-2-with-library
 Server_Utils-1.15.2-1.3.11
 shetiphiancore-1.15-3.7.2
 SilentGear-1.15.2-1.6.4+90
 SilentGems-1.15.2-3.5.3+86
 SilentLib-1.15.2-4.6.1+49
 SilentMechanisms-1.15.2-0.7.1+51
 simplefarming-1.15.2-1.2.9
 SimpleStorageNetwork-1.15.2-0.3.2
 SolarFluxReborn-1.15.2-15.0.0
 solcarrot-1.15.2-1.9.6
 spiketraps-2.0
 StorageDrawers-1.15.2-7.0.2
 structurize-0.10.317-ALPHA
 swingthroughgrass-1.15.2-1.4.0
 tesseract-1.0.5-mc1.15
 The-Endergetic-Expansion-1.15.2-v1.3.1
 themidnight-0.5.7-3
 theoneprobe-1.15-2.0.2
 tinyprogressions-1.15.2-4.0.1
 titanium-1.15.2-2.4.0
 TMechworks-1.15.2-2.1.0
 ToastControl-1.15.2-3.0.1
 torchmaster-2.1.1-rc0
 torchslabmod-1.15.2_v1.6.13
 TrashSlot_1.15.2-11.0.0
 u_team_core-1.15.2-2.11.0.156
 ultra_amplified_dimension-1.15.2-8.0.2
 useful_backpacks-1.15.2-1.9.4.63
 VampiresNeedUmbrellas-1.15.2-1.2
 Vampirism-1.15.2-1.6.0-beta.2
 WaterStrainer-1.15.2-9.0.0
 Waystones_1.15.2-6.0.1
 wetstone-1.2.0
 WitherSkeletonTweaks-1.15.1-4.0.0
 worldedit-forge-mc1.15.2-7.1.0
 wtbw_core-1.15.2-1.0.18
 wtbw_decoration-1.15.2-1.0.16
 wtbw_lib-1.15.2-1.0.20
 wtbw_machines-1.15.2-1.0.23
 wtbw_tools-1.15.2-1.0.20
 xnet-1.15-2.1.3-beta

**Comment by skyjay1** [comment]
1.15 is no longer supported. Sorry for any inconvenience.
