### ISSUE TITLE
Incompatible with Galacticraft

### ISSUE THREAD

**Issue by colbyrobison** [skyjay1/Nomadic-Tents#51]
[crash-2020-07-23_10.20.10-client.txt](https://github.com/skyjay1/Nomadic-Tents/files/4966573/crash-2020-07-23_10.20.10-client.txt)

**Comment by skyjay1** [comment]
As far as I can tell, this crash is due to exceeding the item ID limit. There is nothing Nomadic Tents can do about this, and the user needs to give up some other mods if they want to add this one.

**Comment by colbyrobison** [comment]
I found the solution by installing the Just Enough IDs mod to extend the block limit of my modpack 

https://www.curseforge.com/minecraft/mc-mods/jeid
