### ISSUE TITLE
Tent Spawning inside each other

### ISSUE THREAD

**Issue by sabinoplane** [skyjay1/Nomadic-Tents#53]
So today my friend made a new tent in our "nomadic" world, and in the tent dimension his tent spawned inside mine, destroying a lot of the stuff i had built in my fully upgraded tent and making me lose a lot of items, and causing me to have to jump into creative and fix a lot of things.
Again, latest version of the mod for 1.15.2

**Comment by skyjay1** [comment]
Thanks for the report. How many tents had previously been created in this save? Was the tent entered from the Overworld?

**Comment by P3rf3ctXZer0** [comment]
If I read this correctly his friend attempted to place his tent inside  @sabinoplane 's  tent.

**Comment by sabinoplane** [comment]
The tent was entered from the overworld, yes, and the world had about 4 total tents i think (i think the max amount we got to was like 6, unsure of the exact amount but nothing big)

Also I apologize for the late reply
