### ISSUE TITLE
Please port to 1.16.3 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [skyjay1/Nomadic-Tents#55]
Your mod is one of a kind and I would be more than happy to continuously test your mod. Please consider pushing it to 1.16.3 even if you keep bug fixing 1.12.2

**Comment by greysondn** [comment]
Seconded. We're getting ready to move the server forwards and this is one of the few missing ones that will hurt with almost all major mods supporting 1.16.3 now.

**Comment by Anarchysun85** [comment]
After losing Compact Machines this mod has been amazing. Super fun as a nomadic player and just so unique. Please let us know if an updates in the works. If not then it will be sorely missed in the future modpacks. Thanks for all of your hard work.

**Comment by skyjay1** [comment]
I am very close to releasing a Forge 1.16.5 version, after which I plan to port to Forge 1.18.2 :)
Sorry this took so long, I've been in uni for the last 3 years and had very little free time

**Comment by P3rf3ctXZer0** [comment]
thanks for not forgetting though :D
