### ISSUE TITLE
Missing mod license

### ISSUE THREAD

**Issue by Ratugroote** [skyjay1/Nomadic-Tents#60]
Minecraft says the mod is missing a license and I don't know how to fix it 

PLEASE HELP ME

**Comment by skyjay1** [comment]
Missing License errors only happen for mods using Forge 1.16 and higher.
There is currently no version of this mod for 1.16. You are trying to use a 1.12 mod in a 1.16+ environment.

**Comment by Ratugroote** [comment]
Thank you for the explanation! are you making a 1.16+ version? if not can you suggest any more mods like this? thanks!

**Comment by skyjay1** [comment]
I have my hands full but I intend to make a 1.16 version eventually... There's a mod called Bag of Yurting that may be for your version that's made by a modder I know
