### ISSUE TITLE
1.18.2 layer upgrading broken

### ISSUE THREAD

**Issue by Gitcrafter** [skyjay1/Nomadic-Tents#66]
when trying to upgrade any tent with additional layers, the crafting doesn´t work and when looking up the recipes  in JEI, it shows empty tags for forge:dirt, minecraft:stone_crafting_materials, forge:storage_blocks/iron, forge:storage_blocks/gold, forge:storage_blocks/diamond, however obsidian works

**Comment by Draconvarie** [comment]
I'm using Minecraft Forge version 1.18.2 and I am having this same issue.
