### ISSUE TITLE
Upgrading tent size requires more space to place. 1.16.5

### ISSUE THREAD

**Issue by shayebeadlingkl** [skyjay1/Nomadic-Tents#67]
Every time a tent is upgraded to the next tier it is requiring a space 2 blocks wider and 2 blocks longer every time. I don't think this is supposed to be happening considering the visual of the tent is still the same size as the tiny size and it's not centered.

**Comment by skyjay1** [comment]
Ah, finally somebody explained what they meant by this bug. I'll fix it, thank you
