### ISSUE TITLE
Experience "resets" until updated

### ISSUE THREAD

**Issue by lclc98** [skyjay1/Nomadic-Tents#7]
When traveling between the dimension the experience is reset until you update it with more experience, when it is that state you can't use the experience.
From quickly looking into it, changing
https://github.com/skyjay1/Nomadic-Tents/blob/master-1.12.2/src/main/java/com/yurtmod/block/TileEntityTentDoor.java#L230
to 
`playerMP.changeDimension(dimTo, tel);`

Should fix the issue but I haven't had the chance to look into it.

**Comment by skyjay1** [comment]
Thank you! For some reason that method did not work properly in earlier versions of Minecraft, which is why I was using the PlayerList version. It works now and will be included in the next 1.12 update.

**Comment by skyjay1** [comment]
Using the method you recommended works, but it plays a Nether Portal travel sound that I'm not sure how to cancel. Any suggestions?

**Comment by skyjay1** [comment]
Marking as resolved but leaving open. Solution is to open the config file and enable this option:
`# Use different teleportation code. Does two things:`
`# 1) Updates XP and 2) Plays Nether sound`
`B:"Safe Teleporting"=false`

**Comment by sekelsta** [comment]
The command /xp add @p 0 points fixes the experience if run after exiting. Maybe you could just do whatever that command does?

**Comment by sabinoplane** [comment]
This issue is still happening in the latest 1.15.2 version, not too big of a deal, but annoying specially when you live inside a tent

**Comment by skyjay1** [comment]
This bug does not appear to happen with 1.16.5 version. If it does... there's not much I can do about it 🤷‍♀️
