### ISSUE TITLE
Major Issue - All the recipes are messed up with Nomadic

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [skyjay1/Nomadic-Tents#8]
Every recipe reads small yurt ... The others still work but figuring out the recipes is kind of a nightmare >_<

**Comment by P3rf3ctXZer0** [comment]
Changelog 

https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/releases/tag/mc-1.12.2-IfYouWantItWorkForIt-0010

**Comment by skyjay1** [comment]
Closing as stale and not actually a bug.

**Comment by P3rf3ctXZer0** [comment]
I am okay with you closing the issue but please don't question my basic computer knowledge of the term bug.

A software bug is an error, flaw, failure or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways.

Yes I did google that but it proves I know what "bug" :D

**Comment by P3rf3ctXZer0** [comment]
So unless you intended JEI to fail - it is a bug ^_^

**Comment by skyjay1** [comment]
My apologies. I misunderstood the original post to mean that the recipes and NBT formatting was not working with inter-mod recipe editors. As for JEI, the 9.4.0 update has some fixes that may help with this.

**Comment by P3rf3ctXZer0** [comment]
I will gladly look into it. I love your mod by the way.

**Comment by P3rf3ctXZer0** [comment]
I take it back - I cannot delete a world which I have had for 2 months sorry :( unless hm ... will the old tents break or is it the old tent dimension that will break?

**Comment by skyjay1** [comment]
~~Tent doors will most likely no longer work, and tent items will have the wrong NBT data. Basically, the locations of all your tents will be erased (even though the tents and stuff inside will still be there).  
If you're determined enough, you can follow [these instructions](https://www.curseforge.com/minecraft/mc-mods/nomadic-tents/issues/4) to get new tent items that have the correct NBT location data, and your items will not be affected. Although I don't think the tent copy tool will work and you will need to use complicated /give commands. 
The equation to get the "ID" value ([here](https://github.com/skyjay1/Nomadic-Tents/blob/master-1.12.2/src/main/java/com/yurtmod/block/TileEntityTentDoor.java#L77-L79)) uses the door X and Z positions:  _ID = ( [x] / 32 ) + ( [z] * 2 )_
You could also take everything out of the tents before updating. 
Sorry for the major inconvenience.~~

Taking this into account, I added a functionality for updating tents that _might_ work - deconstruct all of your 9.3.x tents, place them in your inventory, and then update to 9.4.1. The tent item _should_ automatically calculate the correct tent ID and update for you. There may be occasional conflicts when you craft a new tent, so be careful. And as always, make a world backup before trying this.

**Comment by P3rf3ctXZer0** [comment]
thank you. When I get my server host maintenance done - I will try this
