### ISSUE TITLE
[Feature Suggestion] Use Minecraft Schematics to populate interior

### ISSUE THREAD

**Issue by khionu** [skyjay1/Nomadic-Tents#9]
This would be useful for giving players a tent with some basics to start.

**Comment by skyjay1** [comment]
A couple people have suggested supporting configurable "extras" to spawn in a tent, like chests or furnaces or other blocks (see Issue #6 ). Overall I decided that it's a great idea, but it's a little out of scope for this mod. However, there is hope! If you can find a modder who is familiar with Minecraft Schematics (which I'm not), they can do some event-handling to do anything they want when a player enters a tent. See [this comment](https://github.com/skyjay1/Nomadic-Tents/issues/6#issuecomment-491659886) .

**Comment by khionu** [comment]
I see. I might give it a swing. In case I can't get to it, can I ask that you leave this issue open for others to see?

**Comment by skyjay1** [comment]
1.16.5: Tents now use .nbt structure files. More configurable features are planned.
